const SearchData = [
    { id: 1, title: 'Home', url: 'https://www.jackiewyers.beauty/' },
    { id: 2, title: 'About', url: 'https://www.jackiewyers.beauty/about' },
    { id: 3, title: 'Sitemap', url: 'https://www.jackiewyers.beauty/sitemap' },
    { id: 4, title: 'Press', url: 'https://www.jackiewyers.beauty/press' },
    { id: 5, title: 'Subscribe', url: 'https://www.jackiewyers.beauty/subscribe' },
    { id: 6, title: 'Quiz', url: 'https://www.jackiewyers.beauty/quiz' },
    { id: 7, title: 'Vlogs', url: 'https://www.jackiewyers.beauty/vlogs' },
    { id: 8, title: 'Travel', url: 'https://www.jackiewyers.beauty/travel' },
    { id: 9, title: 'Privacy', url: 'https://www.jackiewyers.beauty/privacy' },
    { id: 10, title: 'Fan Art', url: 'https://www.jackiewyers.beauty/fan-art' },
    { id: 11, title: 'Tutorials', url: 'https://www.jackiewyers.beauty/tutorials' },
    { id: 12, title: 'Pop Culture', url: 'https://www.jackiewyers.beauty/popculture' },
    { id: 13, title: 'Time Travel Tutorials', url: 'https://www.jackiewyers.beauty/timetraveltutorials' },
    { id: 14, title: 'Trends', url: 'https://www.jackiewyers.beauty/trends' },
    { id: 15, title: 'Margot Barbie', url: 'https://www.jackiewyers.beauty/margotbarbie' },
    { id: 16, title: 'Latte Makeup', url: 'https://www.jackiewyers.beauty/lattemakeup' },
    { id: 17, title: 'Sugarplum Fairy', url: 'https://www.jackiewyers.beauty/sugarplumfairy' },
    { id: 18, title: 'Sharon Tate Bridal', url: 'https://www.jackiewyers.beauty/sharontatebridal' },
    { id: 19, title: 'Iconic Sharon', url: 'https://www.jackiewyers.beauty/iconicsharon' },
    { id: 20, title: 'Sophia Loren', url: 'https://www.jackiewyers.beauty/sophialoren' },
    { id: 21, title: 'Lana Blog', url: 'https://www.jackiewyers.beauty/lanablog' },
    { id: 22, title: 'Pat McGrath', url: 'https://www.jackiewyers.beauty/patmcgrath' },
    { id: 23, title: 'Victoria Secret', url: 'https://www.jackiewyers.beauty/victoriasecret' },
    { id: 24, title: '2016 Makeup', url: 'https://www.jackiewyers.beauty/2016Makeup' },
    { id: 25, title: 'Twiggy', url: 'https://www.jackiewyers.beauty/twiggy' },
    { id: 26, title: 'Yardley 1965', url: 'https://www.jackiewyers.beauty/yardley1965' },
    { id: 27, title: 'Grace Kelly', url: 'https://www.jackiewyers.beauty/gracekelly' },
    { id: 28, title: 'Balke Blog', url: 'https://www.jackiewyers.beauty/balkeblog' },
    { id: 29, title: 'No Makeup Spring', url: 'https://www.jackiewyers.beauty/nomakeupspring' },
    { id: 30, title: 'Bardot Hairstyles', url: 'https://www.jackiewyers.beauty/bardothairstyles' },
    { id: 31, title: 'Animal Pretty', url: 'https://www.jackiewyers.beauty/animalpretty' },
    { id: 32, title: 'Summer Beauty', url: 'https://www.jackiewyers.beauty/summerbeauty' },  
    { id: 33, title: 'Bridal Makeup', url: 'https://www.jackiewyers.beauty/bridalmakeup' },
  { id: 34, title: 'Bridal', url: 'https://www.jackiewyers.beauty/bridal' },
  { id: 35, title: 'Period Drama', url: 'https://www.jackiewyers.beauty/perioddrama' },
  { id: 36, title: 'Summer Inspo', url: 'https://www.jackiewyers.beauty/summerinspo' },
  { id: 37, title: 'Camera Settings', url: 'https://www.jackiewyers.beauty/camera-settings' },
  { id: 38, title: 'Francesca Bridgerton', url: 'https://www.jackiewyers.beauty/francesca-bridgerton' },
  { id: 39, title: 'Emily in Paris', url: 'https://www.jackiewyers.beauty/emily-in-paris' },
  { id: 40, title: 'Barbie Doll', url: 'https://www.jackiewyers.beauty/barbie-doll' },
  { id: 41, title: 'Barbie Roundup', url: 'https://www.jackiewyers.beauty/barbie-roundup' },
  { id: 42, title: 'Girly Pop Halloween', url: 'https://www.jackiewyers.beauty/girly-pop-halloween' },
  { id: 43, title: 'My Style', url: 'https://www.jackiewyers.beauty/mystyle' },
  { id: 44, title: 'Vintage Vibes Merch', url: 'https://www.jackiewyers.beauty/vintagevibesmerch' },
  { id: 45, title: '90s Vibes', url: 'https://www.jackiewyers.beauty/90sVibes' },
  { id: 46, title: 'Leather and Lace', url: 'https://www.jackiewyers.beauty/leatherandlace' },
  { id: 47, title: 'Retro Floral', url: 'https://www.jackiewyers.beauty/retrofloral' },
  { id: 48, title: 'Barbie Skiing', url: 'https://www.jackiewyers.beauty/barbieskiing' },
  { id: 49, title: 'Black and Leather', url: 'https://www.jackiewyers.beauty/blackandleather' },
  { id: 50, title: 'Cabin Fever', url: 'https://www.jackiewyers.beauty/cabinfever' },
  { id: 51, title: 'Manhattan Cool', url: 'https://www.jackiewyers.beauty/manhattancool' },
  { id: 52, title: 'Fall Little Black Dress', url: 'https://www.jackiewyers.beauty/falllbd' },
  { id: 53, title: 'Dark Florals', url: 'https://www.jackiewyers.beauty/darkflorals' },
  { id: 54, title: 'Central Park Summer', url: 'https://www.jackiewyers.beauty/cpsummer' },
  { id: 55, title: 'Sleek Spring', url: 'https://www.jackiewyers.beauty/sleekspring' },
  { id: 56, title: 'Paris Princess', url: 'https://www.jackiewyers.beauty/parisprincess' },
  { id: 57, title: 'Parisian Chic', url: 'https://www.jackiewyers.beauty/parisianchic' },
  { id: 58, title: 'Vatican Slay', url: 'https://www.jackiewyers.beauty/vaticanslay' },
  { id: 59, title: 'Walking Waiheke', url: 'https://www.jackiewyers.beauty/walkingwaiheke' },
  { id: 60, title: 'Princesscore Paris', url: 'https://www.jackiewyers.beauty/princesscoreparis' },
  { id: 61, title: 'Polka Dot', url: 'https://www.jackiewyers.beauty/polkadot' },
  { id: 62, title: 'Trevi Fountain', url: 'https://www.jackiewyers.beauty/trevifountain' },
  { id: 63, title: 'Summerset', url: 'https://www.jackiewyers.beauty/summerset' },
  { id: 64, title: 'Houndstooth', url: 'https://www.jackiewyers.beauty/houndstooth' },
  { id: 65, title: 'Met Steps', url: 'https://www.jackiewyers.beauty/metsteps' },
  { id: 66, title: 'Paris in NYC', url: 'https://www.jackiewyers.beauty/paris-in-nyc' },
  { id: 67, title: 'Floral Mini', url: 'https://www.jackiewyers.beauty/floral-mini' },
  { id: 68, title: 'Folklore Fairy', url: 'https://www.jackiewyers.beauty/folklore-fairy' },
  { id: 69, title: 'Mont Tremblant', url: 'https://www.jackiewyers.beauty/tremblant' },
  { id: 70, title: 'Hotel Quintessence', url: 'https://www.jackiewyers.beauty/hotelquintessancesummer' },
  { id: 71, title: 'Disney Beach Club Resort', url: 'https://www.jackiewyers.beauty/disneybeachclubresort' },
  { id: 72, title: 'EPCOT', url: 'https://www.jackiewyers.beauty/epcot' },
  { id: 73, title: 'Westgate San Diego', url: 'https://www.jackiewyers.beauty/westgatesandiego' },
  { id: 74, title: 'Andaz Maui', url: 'https://www.jackiewyers.beauty/andazmaui' },
  { id: 75, title: 'Prince of Wales', url: 'https://www.jackiewyers.beauty/princeofwales' },


    { id: 108, title: 'Barbie Beauty Makeup Looks', url: '/barbie-roundup' },
    { id: 109, title: 'Peaches ‘N Cream Barbie Makeup', url: '/barbie-roundup' },
    { id: 110, title: 'Roller Skate Barbie Makeup Tutorial', url: '/barbie-roundup' },
    { id: 111, title: 'Malibu Barbie Aesthetic', url: '/barbie-roundup' },
    { id: 112, title: 'Cherry Pie Picnic Barbie Look', url: '/barbie-roundup' },
    { id: 113, title: 'Brunette Barbiecore Makeup', url: '/barbie-roundup' },
    { id: 114, title: 'Original Barbie Vintage Glamour', url: '/barbie-roundup' },
    { id: 115, title: 'Barbie Movie Makeup', url: '/barbie-roundup' },
    { id: 116, title: 'Jackie Wyers Barbie Tutorials', url: '/barbie-roundup' },
    { id: 117, title: 'Pastel Eyeshadow Makeup', url: '/barbie-roundup' },
    { id: 118, title: 'Iconic Doll Transformations', url: '/barbie-roundup' },
    { id: 119, title: 'Barbie Halloween Costume Ideas', url: '/barbie-roundup' },
    { id: 120, title: 'Bold Red Lips Makeup', url: '/barbie-roundup' },
    { id: 121, title: 'Barbie-Inspired Hairstyles', url: '/barbie-roundup' },
    { id: 122, title: 'Nostalgic Barbie Fashion', url: '/barbie-roundup' },
    { id: 123, title: 'Vintage Barbie-Inspired Looks', url: '/barbie-roundup' },
    { id: 124, title: 'Margot Robbie Barbie Makeup Recreation', url: '/barbie-roundup' },
    { id: 125, title: 'Pastel Florals for Barbiecore', url: '/barbie-roundup' },
    { id: 126, title: 'Bold Accessories for Barbiecore', url: '/barbie-roundup' },
    { id: 127, title: 'Nostalgic 90s Barbie Style', url: '/barbie-roundup' },
    { id: 128, title: 'Doll-Inspired Makeup Tutorials', url: '/barbie-roundup' },
    { id: 129, title: 'Glamorous Barbie Makeup', url: '/barbie-roundup' },
    { id: 130, title: 'Barbie Aesthetic Transformation', url: '/barbie-roundup' },
    { id: 131, title: 'Classic Barbie Makeup and Style', url: '/barbie-roundup' },
    { id: 132, title: 'Retro Chic Barbiecore Fashion', url: '/barbie-roundup' },
    { id: 133, title: 'Barbie-Inspired Beauty Tips', url: '/barbie-roundup' },
    { id: 134, title: 'Pink Makeup for Barbiecore', url: '/barbie-roundup' },
    { id: 135, title: '50s Barbie Looks', url: '/barbie-roundup' },
    { id: 136, title: 'Iconic Doll Fashion Trends', url: '/barbie-roundup' },
    { id: 137, title: 'Step-by-Step Barbie Tutorials', url: '/barbie-roundup' },
    { id: 138, title: 'Jackie Wyers Beauty Tutorials', url: '/barbie-roundup' },
        { id: 139, title: 'Top Barbie Collaborations 2024', url: '/barbie-doll' },
        { id: 140, title: 'Must-Have Barbie Products', url: '/barbie-doll' },
        { id: 141, title: 'Adult Barbie Collectors', url: '/barbie-doll' },
        { id: 142, title: 'Barbie x Stanley', url: '/barbie-doll' },
        { id: 143, title: 'Barbie x FUNBOY', url: '/barbie-doll' },
        { id: 144, title: 'Silkstone Barbie', url: '/barbie-doll' },
        { id: 145, title: 'Barbie x Aldo', url: '/barbie-doll' },
        { id: 146, title: 'Barbie Coffee Table Book', url: '/barbie-doll' },
        { id: 147, title: 'Barbiecore Trends', url: '/barbie-doll' },
        { id: 148, title: 'Jackie Wyers Barbie Content', url: '/barbie-doll' },
        { id: 149, title: 'Barbie Fashion Accessories', url: '/barbie-doll' },
        { id: 150, title: 'Barbie Collectibles 2024', url: '/barbie-doll' },

        { id: 151, title: 'How to Take Better Photos with iPhone 13 Pro Max', url: '/camera-settings' },
        { id: 152, title: 'Best iPhone Camera Settings for Photography', url: '/camera-settings' },
        { id: 153, title: 'Vibrant Photo Settings for iPhone', url: '/camera-settings' },
        { id: 154, title: 'Rule of Thirds Photography Tips', url: '/camera-settings' },
        { id: 155, title: 'iPhone HDR Mode On vs Off', url: '/camera-settings' },
        { id: 156, title: 'Using Portrait Mode on iPhone for Selfies', url: '/camera-settings' },
        { id: 157, title: 'Capturing Night Photos with iPhone 13', url: '/camera-settings' },
        { id: 158, title: 'Natural Light Photography Tips for Mobile', url: '/camera-settings' },
        { id: 159, title: 'Mobile Photography Tips for Beginners', url: '/camera-settings' },
        { id: 160, title: 'Enhancing Mobile Photos with Grid Composition', url: '/camera-settings' },
        { id: 161, title: 'Cleaning iPhone Lens for Sharper Photos', url: '/camera-settings' },
        { id: 162, title: 'Golden Hour Photography with iPhone', url: '/camera-settings' },
        { id: 163, title: 'Optimizing iPhone Photos for Instagram', url: '/camera-settings' },
        { id: 164, title: 'iPhone 13 Pro Max Travel Photography Settings', url: '/camera-settings' },
        { id: 165, title: 'Mobile Editing Tips for Vibrant Photos', url: '/camera-settings' },
        { id: 166, title: 'Canon G7x for Nighttime Photography', url: '/camera-settings' },
        { id: 167, title: 'iPhone 13 Pro Max vs Canon G7x Photo Quality', url: '/camera-settings' },
        { id: 168, title: 'Mastering Low-Light iPhone Photography', url: '/camera-settings' },
        { id: 169, title: 'iPhone Bokeh Effect Photography Tips', url: '/camera-settings' },
        { id: 170, title: 'iPhone Camera Settings for Soft Lighting', url: '/camera-settings' },
            { id: 171, title: 'How to Create a Dragon Braid', url: '/articles/dragon-braid' },
            { id: 172, title: 'Step-by-Step Pull-Through Braid Tutorial', url: '/articles/dragon-braid' },
            { id: 173, title: 'Dragon Braid Tutorial for Long Hair', url: '/articles/dragon-braid' },
            { id: 174, title: 'Braided Hairstyles for Beginners', url: '/articles/dragon-braid' },
            { id: 175, title: 'Easy Voluminous Braid Hairstyles', url: '/articles/dragon-braid' },
            { id: 176, title: 'Faux French Braid Tutorial', url: '/articles/dragon-braid' },
            { id: 177, title: 'Pull-Through Braid with Rubber Bands', url: '/articles/dragon-braid' },
            { id: 178, title: 'Dragon Braid Ideas for Weddings', url: '/articles/dragon-braid' },
            { id: 179, title: 'Long Hair Braid Tutorial 2024', url: '/articles/dragon-braid' },
            { id: 180, title: 'Voluminous Braid Hairstyles', url: '/articles/dragon-braid' },
            { id: 181, title: 'Emily in Paris Fashion Evolution', url: '/emily-in-paris' },
  { id: 182, title: 'Iconic Outfits from Emily in Paris', url: '/emily-in-paris' },
  { id: 183, title: 'Emily Cooper Style Guide', url: '/emily-in-paris' },
  { id: 184, title: 'Makeup Looks from Emily in Paris', url: '/emily-in-paris' },
  { id: 185, title: 'Lily Collins as Emily Cooper', url: '/emily-in-paris' },
  { id: 186, title: 'Patricia Field Fashion Design', url: '/emily-in-paris' },
  { id: 187, title: 'Marylin Fitoussi Costume Styling', url: '/emily-in-paris' },
  { id: 188, title: 'American-in-Paris Chic Outfits', url: '/emily-in-paris' },
  { id: 189, title: 'Bold and Eclectic Fashion Inspiration', url: '/emily-in-paris' },
  { id: 190, title: 'Netflix Fashion Series Style', url: '/emily-in-paris' },
  { id: 191, title: 'Emily in Paris Hair and Makeup Tips', url: '/emily-in-paris' },
  { id: 192, title: 'Audrey Hepburn-Inspired Outfits', url: '/emily-in-paris' },
  { id: 193, title: 'Vibrant Parisian Fashion', url: '/emily-in-paris' },
  { id: 194, title: 'Recreating Emily Cooper’s Style', url: '/emily-in-paris' },
  { id: 195, title: 'Season 1-4 Fashion Recap', url: '/emily-in-paris' },
  { id: 196, title: 'Makeup and Hair Tutorials from Emily in Paris', url: '/emily-in-paris' },
  { id: 197, title: 'TV Show-Inspired Beauty', url: '/emily-in-paris' },
  { id: 198, title: 'Emily in Paris Green Cardigan Style', url: '/emily-in-paris' },
  { id: 199, title: 'Emily Cooper Bold Lipstick Shades', url: '/emily-in-paris' },
  { id: 200, title: 'Thrifting Emily in Paris-Inspired Outfits', url: '/emily-in-paris' },
  { id: 201, title: 'Budget-Friendly Parisian Fashion Looks', url: '/emily-in-paris' },
  { id: 202, title: 'Emily in Paris Season Four Fashion Preview', url: '/emily-in-paris' },
 
    { id: 224, title: 'Girly Halloween Costumes 2024', url: '/girly-pop-halloween' },
    { id: 225, title: 'Britney Spears Schoolgirl Halloween Look', url: '/girly-pop-halloween' },
    { id: 226, title: 'Barbiecore Halloween Ideas', url: '/girly-pop-halloween' },
    { id: 227, title: 'Bridgerton Costume Inspiration', url: '/girly-pop-halloween' },
    { id: 228, title: 'Ariel Little Mermaid Halloween Style', url: '/girly-pop-halloween' },
    { id: 229, title: 'Taylor Swift Betty Folklore Outfit', url: '/girly-pop-halloween' },
    { id: 230, title: 'YSL Haute Couture Bride Recreation', url: '/girly-pop-halloween' },
    { id: 231, title: 'Audrey Hepburn Breakfast at Tiffany’s Costume', url: '/girly-pop-halloween' },
    { id: 232, title: 'Vintage Barbie 1950s Glam Look', url: '/girly-pop-halloween' },
    { id: 233, title: 'Jackie Wyers Halloween Tutorials', url: '/girly-pop-halloween' },
    { id: 234, title: 'Pop Culture Inspired Halloween Costumes', url: '/girly-pop-halloween' },
    { id: 235, title: 'Nostalgic Halloween Outfits', url: '/girly-pop-halloween' },
    { id: 236, title: 'Retro Costume Ideas 2024', url: '/girly-pop-halloween' },
    { id: 237, title: 'Trendy Girly Halloween Styles', url: '/girly-pop-halloween' },
    { id: 238, title: 'DIY Halloween Makeup and Costumes', url: '/girly-pop-halloween' },
    { id: 239, title: 'Celebrity-Inspired Halloween Fashion', url: '/girly-pop-halloween' },
    { id: 240, title: 'Cottagecore Halloween Outfits', url: '/girly-pop-halloween' },
    { id: 241, title: 'Glamorous Halloween Looks', url: '/girly-pop-halloween' },
    { id: 242, title: 'Romantic Halloween Costume Ideas', url: '/girly-pop-halloween' },
    { id: 243, title: 'Halloween 2024 Beauty Trends', url: '/girly-pop-halloween' },
    { id: 271, title: 'Period Drama Makeup', url: '/perioddrama' },
    { id: 272, title: 'Historical Hairstyles', url: '/perioddrama' },
    { id: 273, title: 'No-Makeup Makeup', url: '/perioddrama' },
    { id: 274, title: 'Period Drama Hair Tutorial', url: '/perioddrama' },
    { id: 275, title: 'Tudor Core Aesthetic', url: '/perioddrama' },
    { id: 276, title: 'Jackie Wyers Period Drama Guide', url: '/perioddrama' },
    { id: 277, title: 'Historical Makeup Inspiration', url: '/perioddrama' },
    { id: 278, title: 'Period Drama Beauty Trends', url: '/perioddrama' },
    { id: 279, title: '18th-Century Hairstyles', url: '/perioddrama' },
    { id: 280, title: 'Bridgerton-Inspired Makeup', url: '/perioddrama' },
    { id: 281, title: 'Victorian Hairstyles', url: '/perioddrama' },
    { id: 282, title: 'Edwardian Era Makeup', url: '/perioddrama' },
    { id: 283, title: 'Pirates of the Caribbean Hair Tutorial', url: '/perioddrama' },
    { id: 284, title: 'Little Women Makeup Tutorial', url: '/perioddrama' },
    { id: 285, title: 'Tuck Everlasting Hair and Makeup', url: '/perioddrama' },
    { id: 286, title: 'Blue Lagoon Inspired Hairstyles', url: '/perioddrama' },
    { id: 287, title: 'Historical Beauty Trends', url: '/perioddrama' },
    { id: 288, title: 'Vintage-Inspired Makeup Looks', url: '/perioddrama' },
    { id: 289, title: 'Timeless Makeup Styles', url: '/perioddrama' },
    { id: 290, title: 'Period Piece Beauty Recreations', url: '/perioddrama' },
    { id: 291, title: 'Jackie Wyers Beauty Blog', url: '/perioddrama' },
    { id: 292, title: 'Period Makeup Tutorials', url: '/perioddrama' },
    { id: 293, title: 'Natural Makeup Inspiration', url: '/perioddrama' },
    { id: 294, title: 'Pride and Prejudice Beauty', url: '/perioddrama' },
    { id: 295, title: 'Historical Fiction Beauty Inspiration', url: '/perioddrama' },
    { id: 296, title: 'Rory Gilmore Makeup', url: '/articles/Rory-gilmore' },
  { id: 297, title: 'Gilmore Girls Style', url: '/articles/Rory-gilmore' },
  { id: 298, title: 'No-Makeup Makeup', url: '/articles/Rory-gilmore' },
  { id: 299, title: 'Cozy Fall Fashion', url: '/articles/Rory-gilmore' },
  { id: 300, title: 'Preppy Outfits', url: '/articles/Rory-gilmore' },
  { id: 301, title: 'Rory Gilmore Beauty Tips', url: '/articles/Rory-gilmore' },
  { id: 302, title: 'Stars Hollow Fashion', url: '/articles/Rory-gilmore' },
  { id: 303, title: 'Alexis Bledel Look', url: '/articles/Rory-gilmore' },
  { id: 304, title: 'Fall Wardrobe Inspiration', url: '/articles/Rory-gilmore' },
  { id: 305, title: 'Rory Gilmore Hairstyles', url: '/articles/Rory-gilmore' },
  { id: 306, title: 'Natural Beauty', url: '/articles/Rory-gilmore' },
  { id: 307, title: 'Light Makeup Tutorial', url: '/articles/Rory-gilmore' },
  { id: 308, title: 'Cozy Sweaters', url: '/articles/Rory-gilmore' },
  { id: 309, title: 'Plaid Skirts', url: '/articles/Rory-gilmore' },
  { id: 310, title: 'Preppy Style', url: '/articles/Rory-gilmore' },
  { id: 311, title: 'Bookish Aesthetic', url: '/articles/Rory-gilmore' },
  { id: 312, title: 'Gilmore Girls Filming Locations', url: '/articles/Rory-gilmore' },
  { id: 313, title: 'Unionville Ontario', url: '/articles/Rory-gilmore' },
  { id: 314, title: 'Rory Gilmore Inspired Look', url: '/articles/Rory-gilmore' },
  { id: 315, title: 'Skincare Routine', url: '/articles/Rory-gilmore' },
  { id: 316, title: 'K-Beauty Products', url: '/articles/Rory-gilmore' },
  { id: 317, title: 'Fall Outfits', url: '/articles/Rory-gilmore' },
  { id: 318, title: 'Layered Fashion', url: '/articles/Rory-gilmore' },
  { id: 319, title: 'Stars Hollow Travel', url: '/articles/Rory-gilmore' },
  { id: 320, title: '2000s TV Style', url: '/articles/Rory-gilmore' },
  { id: 321, title: 'Soft Natural Makeup', url: '/articles/Rory-gilmore' },
  { id: 322, title: 'Cherry ChapStick', url: '/articles/Rory-gilmore' },
  { id: 323, title: 'Rory Gilmore Wardrobe', url: '/articles/Rory-gilmore' },
  { id: 324, title: 'Luke’s Diner Vibe', url: '/articles/Rory-gilmore' },
  { id: 325, title: 'Bookish Chic', url: '/articles/Rory-gilmore' },
  { id: 326, title: 'Minimalist Makeup', url: '/articles/Rory-gilmore' },
  { id: 327, title: 'Fall Makeup Guide', url: '/articles/Rory-gilmore' },
  { id: 328, title: 'Gilmore Girls Beauty Tutorial', url: '/articles/Rory-gilmore' },
  { id: 329, title: 'Timeless Beauty Tips', url: '/articles/Rory-gilmore' },
  { id: 330, title: 'Rory Gilmore Outfits', url: '/articles/Rory-gilmore' },
  { id: 331, title: 'Gilmore Girls Fandom', url: '/articles/Rory-gilmore' },
  { id: 332, title: 'Beauty Influencer Tips', url: '/articles/Rory-gilmore' },
  { id: 333, title: 'Jackie Wyers Beauty Blog', url: '/articles/Rory-gilmore' },
  { id: 334, title: 'TV Show Fashion Recreations', url: '/articles/Rory-gilmore' },



    ];
  
  
  export default SearchData;
